### PR TITLE
Allow using a different user to run apache and own the user-files

### PR DESCRIPTION
**Pull request by dabauum221**

### CODE REVIEW

**Comment by sentriz** [comment]
😍

**Comment by Sparh4wk** [comment]
hope that this will be merged soon, looks good :)

**Comment by jpmassena** [comment]
I had to self-build an image from this, I would love for it to be officialy merged!

**Comment by sentriz** [comment]
I also self builded, and noticed that the group stuff wasn't working because I passed `users`, `100` in for `APACHE_RUN_GROUP`, `GROUP_ID` and that group already existed inside the container, so this [line](https://github.com/dabauum221/filerun-docker/blob/e90a481994742b567850609c7468bb8b75be0d25/entrypoint.sh#L7) failed.

my "solution" was to replace [this](https://github.com/dabauum221/filerun-docker/blob/e90a481994742b567850609c7468bb8b75be0d25/entrypoint.sh#L2-L9) with this:
```sh
set -ux

groupmod -g ${APACHE_RUN_GROUP_ID} ${APACHE_RUN_GROUP}
groupadd --gid ${APACHE_RUN_GROUP_ID} ${APACHE_RUN_GROUP}
useradd --uid ${APACHE_RUN_USER_ID} --gid ${APACHE_RUN_GROUP_ID} ${APACHE_RUN_USER}
```
but there's probably a much better way to do it.

then this is my `docker-compose.yml`:
```yml
filerun:
  build: ${BUILD}/filerun_perms
  container_name: filerun
  depends_on:
  - maria
  environment:
  - APACHE_RUN_USER_ID=${PUID}
  - APACHE_RUN_GROUP_ID=${PGID}
  - APACHE_RUN_USER=${USER_NAME}
  - APACHE_RUN_GROUP=${GROUP_NAME}
  - FR_DB_HOST=maria
  - FR_DB_PORT=3306
  - FR_DB_NAME=filerun
  - FR_DB_USER=filerun
  - FR_DB_PASS=filerun
  expose:
  - 80
  labels:
    com.centurylinklabs.watchtower.enable: 'false'
    traefik.docker.network: proxy
    traefik.enable: 'true'
    traefik.frontend.rule: Host:files.${DOMAIN}
  networks:
  - filerun
  - proxy
  restart: unless-stopped
  volumes:
  - ${DATA}/filerun/html:/var/www/html
  - ${MEDIA}:/user-files

maria:
  container_name: maria
  environment:
  - MYSQL_ROOT_PASSWORD=filerun
  - MYSQL_USER=filerun
  - MYSQL_PASSWORD=filerun
  - MYSQL_DATABASE=filerun
  image: mariadb:10.1
  networks:
  - filerun
  restart: unless-stopped
  volumes:
  - ${DATA}/maria/db:/var/lib/mysql
```
along with a `.env`

**Pull request merged**
